### ISSUE TITLE
NEAT networks should support IMLClassification

### ISSUE THREAD

**Issue by jeffheaton** [encog/encog-dotnet-core#86]
Add the helper function to the NEAT networks to support classification.

**Comment by jeffheaton** [comment]
The classification "Classify" function is really just a helper method to be used after the neural network is trained.  Neural networks are usually trained using regression, even if they are eventually to classify.  The RMSE/SME error calculation essentially calculates a vector difference between the actual and expected error over the entire network.  This makes the training more effective, as the strengths of the output neurons determine the confidence in each of the classes.  If the genetic objective function were reduced to just the percent correct, then we would lose quite a bit of information and training would suffer.  For example, the correct class might be class number 1, and two genomes might both select class number 1.  But, whichever genome had the strongest neuron output for class one should get the better score.  Also, the other neurons should be close to zero, and any values above zero should count against it.  The regression error calculation functions all take care of that.

**Comment by KiransHub** [comment]
Looking at the code.. This makes perfect sense. Classification appears to be a sort of facade over a regression problem. Therefore classification taski require regression "under the hood". This actually works out nicely because it gives you an accurate error value which is more accurate than simply checking if the predicted class was correct or not.
